# Generated by Django 6.0.6 on 2026-06-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_member_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='photo',
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
